-- # Of records bought at each store, AVG price spent there
CREATE VIEW VW_SALE_LOCATION_STATS AS
SELECT SALE_LOCATION AS "Location", 
	   CONCAT('$', ROUND( AVG(SALE_PRICE), 2 ) ) AS "Avg Amount Spent",
       CONCAT('$', ROUND( SUM(SALE_PRICE), 2 ) ) AS "Total Amount Spent",
       COUNT(ALBUM_ID) AS "# Of Records Purchased"
FROM SALE
GROUP BY SALE_LOCATION
ORDER BY `# Of Records Purchased` DESC;

-- Most Listened to Albums
CREATE VIEW VW_MOST_LISTENS AS 
SELECT ALBUM_TITLE AS "Album Name", COUNT(SPIN_ID) AS "# Of Spins"
FROM SPIN S
JOIN RECORD R ON R.REC_ID = S.REC_ID
JOIN ALBUM A ON A.ALBUM_ID = R.ALBUM_ID
GROUP BY ALBUM_TITLE
ORDER BY `# Of Spins` DESC; 

-- Most Records from Artists
CREATE VIEW VW_ARTISTS AS
SELECT ALBUM_ARTIST AS "Artist", COUNT(ALBUM_ID) AS "# Of Records"
FROM ALBUM
GROUP BY ALBUM_ARTIST
ORDER BY `# Of Records` DESC;

-- Albums by year
CREATE VIEW VW_ALBUMS_BY_YEAR AS 
SELECT ALBUM_RELEASE_YEAR AS "Year", COUNT(ALBUM_ID) AS "# Of Albums"
FROM ALBUM
GROUP BY ALBUM_RELEASE_YEAR
ORDER BY ALBUM_RELEASE_YEAR;

